channels:
  - anaconda
  - bioconda
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - bedtools
  - biopython
  - blast
  - busco
  - bwa
  - datasketch
  - kmc
  - minimap2
  - pandas
  - scikit-learn
  - scipy
  - plotly
  - seaborn
